
public class MyPicture {

	public static void main(String[] args) {
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZ8MMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOZZZO8DDDZZOMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZ8DDD,$DDZZMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZZZD888Z...8DOZOMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZZZ88DD.....88DZZMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZ8D8Z......8D8ZZMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZ8888.......D8DZZMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZZOD8D........888ZZMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZ888.........~88ZZNMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZZ888+..........8DZZZMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOZZ888...........D8DZZMMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZ888...........:88OZMMMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZO88,............8DZZOMMMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZ8DD.............OD8ZZMMMMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZDDD..............8DZZ8MMM8DMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZDD8.......8......$DDZZMZZZZZZZDMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZ8DD......DD8......D8ZZOZZOD8D8ZZZMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZO88D......88D$......D8ZZMZZ88.O88ZZDMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZD8D......D8DD......8DDZZ8ZZ88..8D8ZZMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZ8D8......8DD8D......8DOZOZZD8Z...88ZZMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZD8......8D8Z8D......8DZZZZDD8....D8ZZMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMOZZ8D......O88OZ88......8DZZZ888.....88ZZMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMNZZ88:.....:88ZZZ88......8DOD887.....8DDZZMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMZZ888......88ZZZZDD......D88DZ.......88ZZMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMZZ888......D8DZZZZ8D?.....DO.........D8ZZOMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMZZ8DD......D88D8888DDO..............D8DZZZMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMZZZZ88......=888DDD,................DDDDOZOMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMZZZZ88D8~...........................,D8D8ZZZMMM.N:+MMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMZZZO8D88,.........................=DDD88OOZZMMMMMOMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMOZZD8D8......................ZDO.....D8ZZZZZMMMMMMZZZZOMMMMMMMMM");
System.out.println("		MMMMDO8MMMMMMMMZZZ888..............7DDDD8DDD8DD8.....D8OZZMMMMMMOZZO8ZZZ8MMMMMMM");
System.out.println("		MMZZZZZZZMMMMMZZO88.............D8D888D8ZZZOZZ88.....?8DZZMMMMMMZZ888D8ZZZMMMMMM");
System.out.println("		MZZ88888OZMMMZZ888.............888ZZZZZZZZONZZ888.....888ZZMMMM8ZO88.,8DOZZMMMMM");
System.out.println("		OZO88.88ZZNMMZZ88....?D,......888ZZMMMMMMMMMMZZ8D......88ZZZMMMMZZ8D...88ZZMMMMM");
System.out.println("		ZZ88~.D88ZZ8OZODD.8888~ .....O8DZZMMMMMMMMMMMOZ888.....,88ZZZMM8ZZ88...D8OZZMMMM");
System.out.println("		ZZ88...88DZZZZZ8888D8.......=D8OZ8MMMMMMMMMMMMZZ88O.....=D8OZZMOZD8O...888ZZMMMM");
System.out.println("		ZZ88....~8888OZZ8888.......~D8ZZOMMMMMMMMMMMMMNZZ88.......888ZZZD88....O88ZZMMMM");
System.out.println("		ZZ88.......8DD8D88........~8DZZOMMMMMMMMMMMMMMMZZO88.......D8D8D88.....D88ZZMMMM");
System.out.println("		ZZ88D....................O88ZZZMMMMMMMMMMMMMMMMMZZO88.........+........D8ZZMMMMM");
System.out.println("		MZZ88D..................D88ZZOMMMMMMMMMMMMMMMMMMMZZZ888...............D88ZZMMMMM");
System.out.println("		MMZZ888...............ZD88ZZNMMMMMMMMMMMMMMMMMMMMMOZZ8D8.............888ZZMMMMMM");
System.out.println("		MMMZZO888~..........8888ZZZMMMMMMMMMMMMMMMMMMMMMMMMNZZOD88$........8888ZZMMMMMMM");
System.out.println("		MMMMZZZZ8DD8DDDD8DDDD8ZZZ8MMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZDDDDD8D8D88DZZZMMMMMMMM");
System.out.println("		MMMMMMZZZZZOD8888D8ZZZZDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOZZZZZ88DOZZZZZMMMMMMMMMM");
System.out.println("		MMMMMMMMMOZZZZZZZZZZ8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZZZZZZOOMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
System.out.println("		MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		
		

	}

}
